import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    always-on-top: true;
    title: "Key Light Control";
    callback request-increase-value();
    // VerticalBox {
    //     Text {
    //         text: "Counter: \{root.counter}";
    //     }

    //     Button {
    //         text: "Increase value";
    //         clicked => {
    //             root.request-increase-value();
    //         }
    //     }
    // }
    GridLayout {
        Row {
            Text {
                text: "Enter IP address";
            }

            input := TextInput {
                text: "192.168.1.1";
            }
        }

        Button {
            text: "Connect";
            clicked => {
                input.focus();
            }
        }
    }
}
